site_name: Cheat Sheet
theme:
    name: 'material'
    palette:
        primary: 'blue'

nav:
    - Introduction: index.md
    - Git: git.md
    - Gitlab_Ci: gitlab_CI.md
    - NLP: nlp.md
    - Terraform: terraform.md

repo_name: https://github.com/Jcch94/cheatsheet
repo_url: https://jcch94.github.io/cheatsheet/

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    
